name: RMotd
version: '1.0'
main: com.adasjusk.rmotd.RMotd
author: adasjusk
api-version: 1.21
commands:
  randommotd:
    description: Toggles the random server motd feature on or off
    permission: rmotd.randommotd
  motd:
    description: MOTD management (default/create/reload)
    permission: rmotd.motd